<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="25171" started-at="2019-01-23T14:35:59Z" finished-at="2019-01-23T14:36:24Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="25171" started-at="2019-01-23T14:35:59Z" finished-at="2019-01-23T14:36:24Z">
      <class name="testcases.TC_002">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TC_002@101df177]" name="setUp" is-config="true" duration-ms="4404" started-at="2019-01-23T14:36:08Z" finished-at="2019-01-23T14:36:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tc_001()[pri:0, instance:testcases.TC_002@101df177]" name="tc_001" duration-ms="3835" started-at="2019-01-23T14:36:13Z" finished-at="2019-01-23T14:36:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_001 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TC_002@101df177]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-23T14:36:16Z" finished-at="2019-01-23T14:36:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TC_002 -->
      <class name="testcases.TC_001">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TC_001@2f490758]" name="setUp" is-config="true" duration-ms="6525" started-at="2019-01-23T14:35:59Z" finished-at="2019-01-23T14:36:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tc_001()[pri:0, instance:testcases.TC_001@2f490758]" name="tc_001" duration-ms="3037" started-at="2019-01-23T14:36:05Z" finished-at="2019-01-23T14:36:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_001 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TC_001@2f490758]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-23T14:36:08Z" finished-at="2019-01-23T14:36:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="generateReport()[pri:0, instance:testcases.TC_001@2f490758]" name="generateReport" is-config="true" duration-ms="4558" started-at="2019-01-23T14:36:24Z" finished-at="2019-01-23T14:36:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
      </class> <!-- testcases.TC_001 -->
      <class name="testcases.TC_003">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TC_003@166fa74d]" name="setUp" is-config="true" duration-ms="4427" started-at="2019-01-23T14:36:16Z" finished-at="2019-01-23T14:36:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="tc_001()[pri:0, instance:testcases.TC_003@166fa74d]" name="tc_001" duration-ms="1964" started-at="2019-01-23T14:36:21Z" finished-at="2019-01-23T14:36:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testcases.TC_003.tc_001(TC_003.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_001 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TC_003@166fa74d]" name="tearDown" is-config="true" duration-ms="899" started-at="2019-01-23T14:36:23Z" finished-at="2019-01-23T14:36:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TC_003 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
